### ISSUE TITLE
KeyError: 'started'

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#143]
A recent run on datalad logs

`Cron <datalad@smaug> chronic flock -n -E 0 /home/datalad/.run/tinuous-datalad.lock /mnt/datasets/datalad/ci/logs/tools/cron_job` crashed with

```
2022-01-26T10:00:24-0500 [INFO    ] tinuous Downloading logs for job 13313.5 to 2022/01/26/pr/6378/12238ff/travis-13313-incomplete/5.txt
2022-01-26T10:00:25-0500 [INFO    ] tinuous Downloading logs for job 13313.6 to 2022/01/26/pr/6378/12238ff/travis-13313-incomplete/6.txt
Traceback (most recent call last):
  File "/home/datalad/miniconda3/envs/tinuous-dev/bin/tinuous", line 33, in <module>
    sys.exit(load_entry_point('tinuous', 'console_scripts', 'tinuous')())
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 119, in fetch
    path = obj.expand_path(cicfg.paths.logs, cfg.vars)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/base.py", line 234, in expand_path
    return expand_template(path_template, self.path_fields(), vars)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/travis.py", line 179, in path_fields
    fields = super().path_fields()
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/base.py", line 230, in path_fields
    "common_status": COMMON_STATUS_MAP[self.status],
KeyError: 'started'
```
I guess we can't expect that field for incomplete?

**Comment by jwodder** [comment]
Status mapped to "incomplete", though I'm curious how a build with a job in "started" state was able to have a "finished_at" timestamp, which it would have needed in order for tinuous to not skip the build due to it still being in progress.  Checking the build via the API doesn't help, as there the job state seems to have already been updated to "failed" — and the [web build history](https://app.travis-ci.com/github/datalad/datalad/builds) doesn't list any builds past 13311 at the moment.
