### ISSUE TITLE
AttributeError: 'Repository' object has no attribute 'get_workflow'

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#15]
config from README.md, on top of previously collected logs (may be relevant? then I could share what I have)

```
$> ( source $PWD.secrets ; tools/tinuous/tinuous -c tinuous-config.yaml; )         
2021-02-17T19:51:20-0500 [INFO    ] tinuous Fetching logs from github
2021-02-17T19:51:20-0500 [INFO    ] tinuous Fetching runs newer than 2021-01-20 00:00:00+00:00
Traceback (most recent call last):
  File "tools/tinuous/tinuous", line 697, in <module>
    main()
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "tools/tinuous/tinuous", line 667, in main
    for bl in ci.get_build_logs(event_types):
  File "tools/tinuous/tinuous", line 152, in get_build_logs
    wf = repo.get_workflow(wffile)
AttributeError: 'Repository' object has no attribute 'get_workflow'

$> git -C tools/tinuous/ describe --always                                
764fc84
```

**Comment by jwodder** [comment]
@yarikoptic What version of PyGithub do you have installed?  The `requirements.txt` file specifies at least 1.53, and I think `get_workflow()` was introduced in 1.52.

**Comment by yarikoptic** [comment]
seems to be good enough:
```
(git)smaug:~datalad/ci/logs[master]git
$> python -c 'import pkg_resources; print(pkg_resources.get_distribution("pygithub"));import github; print(github.__version__)'
PyGithub 1.54.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'github' has no attribute '__version__'
```

<details>
<summary>pip freeze</summary> 

```shell
$> pip freeze
annexremote @ file:///home/conda/feedstock_root/build_artifacts/annexremote_1613448384953/work
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
boto==2.49.0
brotlipy==0.7.0
certifi==2020.12.5
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1613413861439/work
cfgv @ file:///home/conda/feedstock_root/build_artifacts/cfgv_1596220740692/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1610093490430/work
click==7.1.2
click-loglevel==0.2.0
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1612993729974/work
datalad @ file:///home/conda/feedstock_root/build_artifacts/datalad_1612389217376/work
Deprecated==1.2.11
distro @ file:///home/conda/feedstock_root/build_artifacts/distro_1591810140801/work
ExifRead==2.1.2
fasteners==0.14.1
future @ file:///home/conda/feedstock_root/build_artifacts/future_1610147327521/work
humanize @ file:///home/conda/feedstock_root/build_artifacts/humanize_1607797768772/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
iso8601 @ file:///home/conda/feedstock_root/build_artifacts/iso8601_1599859615338/work
jeepney @ file:///home/conda/feedstock_root/build_artifacts/jeepney_1605811727098/work
jsmin==2.2.2
keyring @ file:///home/conda/feedstock_root/build_artifacts/keyring_1611767820968/work
keyrings.alt @ file:///home/conda/feedstock_root/build_artifacts/keyrings.alt_1608136994844/work
monotonic==1.5
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1610121699837/work
mutagen==1.41.1
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
patool @ file:///home/conda/feedstock_root/build_artifacts/patool_1610146224020/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1612816714926/work
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1610127095720/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
PyGithub==1.54.1
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1610910308735/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyperclip @ file:///home/conda/feedstock_root/build_artifacts/pyperclip_1610639094381/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1610291447907/work
python-dateutil==2.8.1
PyYAML==5.4.1
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1608156231189/work
requests-ftp @ file:///home/conda/feedstock_root/build_artifacts/requests-ftp_1602638041394/work
SecretStorage @ file:///home/conda/feedstock_root/build_artifacts/secretstorage_1612911537506/work
simplejson @ file:///home/conda/feedstock_root/build_artifacts/simplejson_1610147072101/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1612992512436/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1611695416663/work
Whoosh==2.7.4
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1610094884173/work
```

</details>

<details>
<summary>here is what repo has</summary> 

```shell
(Pdb) p repo
Repository(full_name="datalad/datalad")
(Pdb) p dir(repo)
['CHECK_AFTER_INIT_FLAG', '_CompletableGithubObject__complete', '_CompletableGithubObject__completed', '_GithubObject__makeSimple
Attribute', '_GithubObject__makeSimpleListAttribute', '_GithubObject__makeTransformedAttribute', '_Repository__create_pull', '_Re
pository__create_pull_1', '_Repository__create_pull_2', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '
__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__
', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_
_weakref__', '_allow_merge_commit', '_allow_rebase_merge', '_allow_squash_merge', '_archive_url', '_archived', '_assignees_url', 
'_blobs_url', '_branches_url', '_clone_url', '_collaborators_url', '_comments_url', '_commits_url', '_compare_url', '_completeIfN
eeded', '_completeIfNotSet', '_contents_url', '_contributors_url', '_created_at', '_default_branch', '_description', '_downloads_
url', '_events_url', '_fork', '_forks', '_forks_count', '_forks_url', '_full_name', '_git_commits_url', '_git_refs_url', '_git_ta
gs_url', '_git_url', '_has_downloads', '_has_issues', '_has_projects', '_has_wiki', '_headers', '_homepage', '_hooks_url', '_html
_url', '_hub', '_id', '_identity', '_initAttributes', '_issue_comment_url', '_issue_events_url', '_issues_url', '_keys_url', '_la
bels_url', '_language', '_languages_url', '_legacy_convert_issue', '_makeBoolAttribute', '_makeClassAttribute', '_makeDatetimeAtt
ribute', '_makeDictAttribute', '_makeDictOfStringsToClassesAttribute', '_makeIntAttribute', '_makeListOfClassesAttribute', '_make
ListOfDictsAttribute', '_makeListOfIntsAttribute', '_makeListOfListOfStringsAttribute', '_makeListOfStringsAttribute', '_makeStri
ngAttribute', '_makeTimestampAttribute', '_master_branch', '_merges_url', '_milestones_url', '_mirror_url', '_name', '_network_co
unt', '_notifications_url', '_open_issues', '_open_issues_count', '_organization', '_owner', '_parent', '_parentUrl', '_permissio
ns', '_private', '_pulls_url', '_pushed_at', '_rawData', '_requester', '_size', '_source', '_ssh_url', '_stargazers_count', '_sta
rgazers_url', '_statuses_url', '_storeAndUseAttributes', '_subscribers_count', '_subscribers_url', '_subscription_url', '_svn_url
', '_tags_url', '_teams_url', '_topics', '_trees_url', '_updated_at', '_url', '_useAttributes', '_watchers', '_watchers_count', '
add_to_collaborators', 'allow_merge_commit', 'allow_rebase_merge', 'allow_squash_merge', 'archive_url', 'archived', 'assignees_ur
l', 'blobs_url', 'branches_url', 'clone_url', 'collaborators_url', 'comments_url', 'commits_url', 'compare', 'compare_url', 'cont
ents_url', 'contributors_url', 'create_file', 'create_git_blob', 'create_git_commit', 'create_git_ref', 'create_git_release', 'cr
eate_git_tag', 'create_git_tag_and_release', 'create_git_tree', 'create_hook', 'create_issue', 'create_key', 'create_label', 'cre
ate_milestone', 'create_project', 'create_pull', 'create_source_import', 'created_at', 'default_branch', 'delete', 'delete_file',
 'description', 'disable_automated_security_fixes', 'disable_vulnerability_alert', 'downloads_url', 'edit', 'enable_automated_sec
urity_fixes', 'enable_vulnerability_alert', 'etag', 'events_url', 'fork', 'forks', 'forks_count', 'forks_url', 'full_name', 'get_
_repr__', 'get_archive_link', 'get_assignees', 'get_branch', 'get_branches', 'get_clones_traffic', 'get_collaborator_permission',
 'get_collaborators', 'get_comment', 'get_comments', 'get_commit', 'get_commits', 'get_contents', 'get_contributors', 'get_dir_co
ntents', 'get_download', 'get_downloads', 'get_events', 'get_forks', 'get_git_blob', 'get_git_commit', 'get_git_ref', 'get_git_re
fs', 'get_git_tag', 'get_git_tree', 'get_hook', 'get_hooks', 'get_issue', 'get_issues', 'get_issues_comments', 'get_issues_event'
, 'get_issues_events', 'get_key', 'get_keys', 'get_label', 'get_labels', 'get_languages', 'get_latest_release', 'get_license', 'g
et_milestone', 'get_milestones', 'get_network_events', 'get_notifications', 'get_pending_invitations', 'get_projects', 'get_pull'
, 'get_pulls', 'get_pulls_comments', 'get_pulls_review_comments', 'get_readme', 'get_release', 'get_release_asset', 'get_releases
', 'get_source_import', 'get_stargazers', 'get_stargazers_with_dates', 'get_stats_code_frequency', 'get_stats_commit_activity', '
get_stats_contributors', 'get_stats_participation', 'get_stats_punch_card', 'get_subscribers', 'get_tags', 'get_teams', 'get_top_
paths', 'get_top_referrers', 'get_topics', 'get_views_traffic', 'get_vulnerability_alert', 'get_watchers', 'git_commits_url', 'gi
t_refs_url', 'git_tags_url', 'git_url', 'has_downloads', 'has_in_assignees', 'has_in_collaborators', 'has_issues', 'has_projects'
, 'has_wiki', 'homepage', 'hooks_url', 'html_url', 'id', 'issue_comment_url', 'issue_events_url', 'issues_url', 'keys_url', 'labe
ls_url', 'language', 'languages_url', 'last_modified', 'legacy_search_issues', 'mark_notifications_as_read', 'master_branch', 'me
rge', 'merges_url', 'milestones_url', 'mirror_url', 'name', 'network_count', 'notifications_url', 'open_issues', 'open_issues_cou
nt', 'organization', 'owner', 'parent', 'permissions', 'private', 'pulls_url', 'pushed_at', 'raw_data', 'raw_headers', 'remove_fr
om_collaborators', 'remove_invitation', 'replace_topics', 'setCheckAfterInitFlag', 'size', 'source', 'ssh_url', 'stargazers_count
', 'stargazers_url', 'statuses_url', 'subscribe_to_hub', 'subscribers_count', 'subscribers_url', 'subscription_url', 'svn_url', '
tags_url', 'teams_url', 'topics', 'trees_url', 'unsubscribe_from_hub', 'update', 'update_file', 'updated_at', 'url', 'watchers', 
'watchers_count']

```

*(Pdb) p [x for x in dir(repo) if x.startswith('get_')]
['get__repr__', 'get_archive_link', 'get_assignees', 'get_branch', 'get_branches', 'get_clones_traffic', 'get_collaborator_permis
sion', 'get_collaborators', 'get_comment', 'get_comments', 'get_commit', 'get_commits', 'get_contents', 'get_contributors', 'get_
dir_contents', 'get_download', 'get_downloads', 'get_events', 'get_forks', 'get_git_blob', 'get_git_commit', 'get_git_ref', 'get_
git_refs', 'get_git_tag', 'get_git_tree', 'get_hook', 'get_hooks', 'get_issue', 'get_issues', 'get_issues_comments', 'get_issues_
event', 'get_issues_events', 'get_key', 'get_keys', 'get_label', 'get_labels', 'get_languages', 'get_latest_release', 'get_licens
e', 'get_milestone', 'get_milestones', 'get_network_events', 'get_notifications', 'get_pending_invitations', 'get_projects', 'get
_pull', 'get_pulls', 'get_pulls_comments', 'get_pulls_review_comments', 'get_readme', 'get_release', 'get_release_asset', 'get_re
leases', 'get_source_import', 'get_stargazers', 'get_stargazers_with_dates', 'get_stats_code_frequency', 'get_stats_commit_activi
ty', 'get_stats_contributors', 'get_stats_participation', 'get_stats_punch_card', 'get_subscribers', 'get_tags', 'get_teams', 'ge
t_top_paths', 'get_top_referrers', 'get_topics', 'get_views_traffic', 'get_vulnerability_alert', 'get_watchers']
```
</details>

**Comment by jwodder** [comment]
Cannot reproduce.  Fetching GitHub logs using PyGithub 1.54.1 works fine for me, [and it works fine for con/tinuous-inception](https://github.com/con/tinuous-inception/runs/1923118161?check_suite_focus=true).

**Comment by yarikoptic** [comment]
I think it was some conda environments intricacy.  Probably older (1.44) was first installed but not uninstalled whenever `pip install -e ` was ran for con/tineous -- it rather installed it in addition. I have uninstalled it in the environment and then reinstalled with --upgrade which showed that older one then was finally uninstalled:

```
$> pip install --upgrade pygithub
Requirement already satisfied: pygithub in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (1.44)
WARNING: Keyring is skipped due to an exception: Keyring config exists only in the old location /home/yoh/.local/share/python_keyring/keyringrc.cfg and should be moved to /home/yoh/.config/python_keyring/keyringrc.cfg to work with this version of keyring.
Collecting pygithub
  Using cached PyGithub-1.54.1-py3-none-any.whl (289 kB)
Requirement already satisfied: requests>=2.14.0 in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from pygithub) (2.25.1)
Requirement already satisfied: pyjwt<2.0 in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from pygithub) (1.7.1)
Requirement already satisfied: deprecated in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from pygithub) (1.2.11)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from requests>=2.14.0->pygithub) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from requests>=2.14.0->pygithub) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from requests>=2.14.0->pygithub) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from requests>=2.14.0->pygithub) (2.10)
Requirement already satisfied: wrapt<2,>=1.10 in /home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages (from deprecated->pygithub) (1.12.1)
Installing collected packages: pygithub
  Attempting uninstall: pygithub
    Found existing installation: PyGithub 1.44
    Uninstalling PyGithub-1.44:
      Successfully uninstalled PyGithub-1.44
Successfully installed pygithub-1.54.1
```
and now it runs.
