### ISSUE TITLE
errors out for bids-specification with pydantic_core.ValidationError

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#193]
I found that we disabled cron job for it and have a comment
```
# TEMP: merging with circle ci additions
```

so I reran (using new helper `/mnt/datasets/datalad/ci/cron_job bids-specification` on datalad@smaug) and it crashes with

```
2024-09-06T13:46:07-0400 [INFO    ] tinuous: Fetching releases newer than 2024-08-07 17:27:42.442447+00:00
2024-09-06T13:46:07-0400 [INFO    ] tinuous: Found release v1.10.0
2024-09-06T13:46:07-0400 [INFO    ] tinuous: Fetching resources from circleci
2024-09-06T13:46:07-0400 [INFO    ] tinuous: Fetching pipelines newer than 2022-07-18 00:00:00+00:00
Traceback (most recent call last):
  File "/home/datalad/miniconda3/envs/tinuous-dev/bin/tinuous", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 118, in fetch
    for obj in ci.get_build_assets(
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/circleci.py", line 98, in get_build_assets
    for pipeline in self.get_pipelines():
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/circleci.py", line 68, in get_pipelines
    yield Pipeline.model_validate(item)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.12/site-packages/pydantic/main.py", line 567, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Pipeline
trigger.type
  Input should be 'scheduled-pipeline', 'explicit', 'api', 'webhook' or 'Decoupled Ingestion System' [type=enum, input_value='unknown', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/enum
datalad@smaug:/mnt/datasets/datalad/ci$ /mnt/datasets/datalad/ci/cron_job bids-specification
```

**Comment by yarikoptic** [comment]
> Is this new error also for bids-specification on CircleCI? 

it seems it is an old error, and indeed on circleci

> Could you provide the tinuous.yaml file?

<details>
<summary>here it is from smaug:/mnt/datasets/datalad/ci/bids-specification/tinuous.yaml </summary> 

```yaml
repo: bids-standard/bids-specification
vars:
  path_prefix: '{year}//{month}//{day}/{type}/{type_id}/{commit[:7]}/{ci}-'
  common_path: '{path_prefix}{wf_name}-{number}-{common_status}/'
ci:
  github:
    paths:
      logs: '{common_path}'
      artifacts: '{common_path}'
      releases: 'releases/{release_tag}'
  circleci:
    paths:
      logs: '{common_path}{job_name}/{step}-{index}.txt'
since: 2022-07-18T00:00:00Z
types: [cron, pr, push, manual]
datalad:
  enabled: true
  cfg_proc: text2git
```
</details>

your ssh key `jwodder@Johns-MacBook-Pro.local` allows you to access datalad@smaug so you could inspect in place -- that cron job is disabled ATM: 

```shell
datalad@smaug:~$ crontab -l | grep bids-spe
# 5 3 * * * chronic /mnt/datasets/datalad/ci/cron_job bids-specification
```
```
