### ISSUE TITLE
missing some mkdir

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#3]
based on the example spec in readme, run `datalad run -m "A sample run of tinuous" tools/tinuous/tinuous -c tinuous-config.yaml` failed when got to travis:

```
2021-02-02T16:37:10-0500 [INFO    ] tinuous Downloading logs for test_macos.yml (Test on macOS) #740 to 2021/01/20/github/pr/UNK/c8149832411f908999d4b0b2ec41fe351feccede/Test on macOS/740
2021-02-02T16:37:10-0500 [INFO    ] tinuous Fetching logs from travis
Traceback (most recent call last):
  File "tools/tinuous/tinuous", line 491, in <module>
    main()
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "tools/tinuous/tinuous", line 470, in main
    token=cls.get_auth_token(),
  File "tools/tinuous/tinuous", line 238, in get_auth_token
    r = subprocess.run(
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'travis'

```

**Comment by jwodder** [comment]
The problem is that you don't have the `travis` CLI installed (and `TRAVIS_TOKEN`) isn't set.  Follow the instructions at the bottom of the README for setting up Travis authentication.

**Comment by yarikoptic** [comment]
oh, then it would be nice if the tool should fail with some more informative message, e.g. "travis client (a non-PyPI dependency) is missing, see https://github.com/con/tinuous#travis". Ideally such a check should happen before initiating any actual action
