### ISSUE TITLE
yikes -- TypeError: string indices must be integers 

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#39]
<details>
<summary>tried with that config I suggested with `{commit[:8]}`</summary> 

```shell
$> (source ../logs.secrets && python -m pdb `which tinuous` -c tinuous-config.yaml fetch; )
> /home/yoh/miniconda3/envs/tinuous/bin/tinuous(3)<module>()
-> import re
(Pdb) c
2021-04-28T15:15:25-0400 [INFO    ] tinuous Fetching logs from github
2021-04-28T15:15:25-0400 [INFO    ] tinuous Fetching runs newer than 2021-04-27 00:00:00+00:00
2021-04-28T15:15:25-0400 [INFO    ] tinuous Fetching runs for workflow .github/workflows/benchmarks.yml (Benchmarks)
2021-04-28T15:15:26-0400 [INFO    ] tinuous Found run 2987
Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/pdb.py", line 1704, in main
    pdb._runscript(mainpyfile)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/yoh/miniconda3/envs/tinuous/bin/tinuous", line 3, in <module>
    import re
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/tinuous/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/yoh/proj/datalad/ci/tinuous/src/tinuous/__main__.py", line 776, in fetch
    path = bl.expand_path(cicfg.path)
  File "/home/yoh/proj/datalad/ci/tinuous/src/tinuous/__main__.py", line 131, in expand_path
    return path_template.format_map(self.path_fields())
TypeError: string indices must be integers
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/yoh/proj/datalad/ci/tinuous/src/tinuous/__main__.py(131)expand_path()
-> return path_template.format_map(self.path_fields())
(Pdb) p path_template
'{year}/{month}/{day}/{ci}/{type}/{type_id}/{commit[:8]}/{wf_name}/{number}-{common_status}/'

*(Pdb) p self.path_fields()['commit']
'01be66f64ee1313696f5ccab4ee6a1e22419c600'

(Pdb) p path_template.format_map(self.path_fields())
*** TypeError: string indices must be integers

*(Pdb) p path_template.format(**self.path_fields())
*** TypeError: string indices must be integers

*(Pdb) p '{commit}'.format_map(self.path_fields())
'01be66f64ee1313696f5ccab4ee6a1e22419c600'

*(Pdb) p '{commit[:1]}'.format_map(self.path_fields())
*** TypeError: string indices must be integers

[1]  + 110884 suspended  ( source ../logs.secrets && python -m pdb `which tinuous` -c  fetch; )

```
</details>

apparently it could be used in f-strings, but not in `format`?

```shell
$> python3.9
Python 3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print('{commit[:8]}'.format(commit='123123123'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string indices must be integers
*>>> commit='123123123'
*>>> print(f'{commit[:8]}')
12312312
```

**Comment by yarikoptic** [comment]
ok, I guess if nothing what could be done, let's proceed with #40
