### ISSUE TITLE
automagically wait whenever "rate exceeded"

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#51]
making another attempt at establishing logs fetching for datalad.  Did from just yesterday but it lead to
```
Traceback (most recent call last):
  File "/home/datalad/miniconda3/envs/tinuous-dev/bin/tinuous", line 33, in <module>
    sys.exit(load_entry_point('tinuous', 'console_scripts', 'tinuous')())
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 989, in fetch
    for obj in ci.get_assets(cfg.types, artifacts=get_artifacts):
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 219, in get_assets
    event_id = self.get_event_id(run, run_event)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 252, in get_event_id
    self.client.search_issues(
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 22943981.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

I think `tinuous` should issue a warning and otherwise handle it gracefully and introduce waiting (not sure if any detail such as `Retry-After` percolates to tinuous, but may be could be asked via API). FWIW got only about 400 logs and only for Benchmarks workflow from github, which "inspired" me to file #50.

**Comment by yarikoptic** [comment]
smth isn't right or changed... I can't really fetch much -- created a new token and what I get is just

<details>
<summary>this much on a fresh run after a night of sleep</summary> 

```shell
(tinuous-dev) datalad@smaug:/mnt/datasets/datalad/ci/logs$ ( source $PWD.secrets && tinuous fetch )
2021-05-21T08:44:04-0400 [INFO    ] tinuous Fetching resources from github
2021-05-21T08:44:04-0400 [INFO    ] tinuous Fetching runs newer than 2021-05-19 00:00:00+00:00
2021-05-21T08:44:04-0400 [INFO    ] tinuous Fetching runs for workflow .github/workflows/benchmarks.yml (Benchmarks)
2021-05-21T08:44:06-0400 [INFO    ] tinuous Found run 3113
2021-05-21T08:44:06-0400 [INFO    ] tinuous Downloading logs for benchmarks.yml (Benchmarks) #3113 to 2021/05/21/pr/5690/02fa519/github-Benchmarks-3113-success
2021-05-21T08:44:07-0400 [INFO    ] tinuous Found run 3112
2021-05-21T08:44:07-0400 [INFO    ] tinuous Downloading logs for benchmarks.yml (Benchmarks) #3112 to 2021/05/21/pr/UNK/68f5074/github-Benchmarks-3112-success
2021-05-21T08:44:08-0400 [INFO    ] tinuous Found run 3111
2021-05-21T08:44:08-0400 [INFO    ] tinuous Downloading logs for benchmarks.yml (Benchmarks) #3111 to 2021/05/21/pr/5689/e584dbf/github-Benchmarks-3111-success
2021-05-21T08:44:09-0400 [INFO    ] tinuous Found run 3110
2021-05-21T08:44:09-0400 [INFO    ] tinuous Downloading logs for benchmarks.yml (Benchmarks) #3110 to 2021/05/21/pr/5688/8e8ae6a/github-Benchmarks-3110-success
2021-05-21T08:44:09-0400 [INFO    ] tinuous Found run 3109
2021-05-21T08:44:09-0400 [INFO    ] tinuous Downloading logs for benchmarks.yml (Benchmarks) #3109 to 2021/05/20/pr/UNK/96ceab1/github-Benchmarks-3109-success
2021-05-21T08:44:10-0400 [INFO    ] tinuous Found run 3108
2021-05-21T08:44:10-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3108 already downloaded to 2021/05/20/pr/5667/1424902/github-Benchmarks-3108-success; skipping
2021-05-21T08:44:10-0400 [INFO    ] tinuous Found run 3107
2021-05-21T08:44:10-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3107 already downloaded to 2021/05/20/pr/5687/146f97a/github-Benchmarks-3107-success; skipping
2021-05-21T08:44:10-0400 [INFO    ] tinuous Found run 3106
2021-05-21T08:44:11-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3106 already downloaded to 2021/05/20/pr/5686/dc79cf4/github-Benchmarks-3106-success; skipping
2021-05-21T08:44:11-0400 [INFO    ] tinuous Found run 3105
2021-05-21T08:44:11-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3105 already downloaded to 2021/05/20/pr/UNK/dd36b82/github-Benchmarks-3105-success; skipping
2021-05-21T08:44:11-0400 [INFO    ] tinuous Found run 3104
2021-05-21T08:44:11-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3104 already downloaded to 2021/05/20/pr/5682/748e934/github-Benchmarks-3104-success; skipping
2021-05-21T08:44:11-0400 [INFO    ] tinuous Found run 3103
2021-05-21T08:44:11-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3103 already downloaded to 2021/05/20/pr/5683/2b13bd5/github-Benchmarks-3103-success; skipping
2021-05-21T08:44:11-0400 [INFO    ] tinuous Found run 3102
2021-05-21T08:44:11-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3102 already downloaded to 2021/05/20/pr/5676/5f1ea26/github-Benchmarks-3102-success; skipping
2021-05-21T08:44:11-0400 [INFO    ] tinuous Found run 3101
2021-05-21T08:44:11-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3101 already downloaded to 2021/05/20/pr/UNK/dfe7a7c/github-Benchmarks-3101-success; skipping
2021-05-21T08:44:11-0400 [INFO    ] tinuous Found run 3100
2021-05-21T08:44:11-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3100 already downloaded to 2021/05/20/pr/5667/e8e43ff/github-Benchmarks-3100-success; skipping
2021-05-21T08:44:11-0400 [INFO    ] tinuous Found run 3099
2021-05-21T08:44:12-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3099 already downloaded to 2021/05/20/pr/5667/144f8f9/github-Benchmarks-3099-success; skipping
2021-05-21T08:44:12-0400 [INFO    ] tinuous Found run 3098
2021-05-21T08:44:12-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3098 already downloaded to 2021/05/20/pr/5681/f3d0661/github-Benchmarks-3098-success; skipping
2021-05-21T08:44:12-0400 [INFO    ] tinuous Found run 3097
2021-05-21T08:44:12-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3097 already downloaded to 2021/05/20/pr/UNK/aa3c9c6/github-Benchmarks-3097-success; skipping
2021-05-21T08:44:12-0400 [INFO    ] tinuous Found run 3096
2021-05-21T08:44:12-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3096 already downloaded to 2021/05/20/pr/UNK/69c3426/github-Benchmarks-3096-success; skipping
2021-05-21T08:44:12-0400 [INFO    ] tinuous Found run 3095
2021-05-21T08:44:12-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3095 already downloaded to 2021/05/20/pr/UNK/54fa685/github-Benchmarks-3095-success; skipping
2021-05-21T08:44:12-0400 [INFO    ] tinuous Found run 3094
2021-05-21T08:44:12-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3094 already downloaded to 2021/05/20/pr/5667/7f6cc85/github-Benchmarks-3094-success; skipping
2021-05-21T08:44:12-0400 [INFO    ] tinuous Found run 3093
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3093 already downloaded to 2021/05/20/pr/5680/f75c731/github-Benchmarks-3093-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3092
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3092 already downloaded to 2021/05/20/pr/5667/7f18e9f/github-Benchmarks-3092-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3091
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3091 already downloaded to 2021/05/20/pr/5673/2e14fa7/github-Benchmarks-3091-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3090
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3090 already downloaded to 2021/05/20/pr/UNK/a456f2b/github-Benchmarks-3090-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3089
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3089 already downloaded to 2021/05/19/pr/5676/0bf0cb0/github-Benchmarks-3089-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3088
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3088 already downloaded to 2021/05/19/pr/5675/03b2ced/github-Benchmarks-3088-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3087
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3087 already downloaded to 2021/05/19/push/master/fd7229a/github-Benchmarks-3087-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3086
2021-05-21T08:44:13-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3086 already downloaded to 2021/05/19/push/maint/0c6d355/github-Benchmarks-3086-success; skipping
2021-05-21T08:44:13-0400 [INFO    ] tinuous Found run 3085
2021-05-21T08:44:14-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3085 already downloaded to 2021/05/19/pr/5667/d1888cf/github-Benchmarks-3085-success; skipping
2021-05-21T08:44:14-0400 [INFO    ] tinuous Found run 3084
2021-05-21T08:44:14-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3084 already downloaded to 2021/05/19/pr/5674/1bad217/github-Benchmarks-3084-success; skipping
2021-05-21T08:44:15-0400 [INFO    ] tinuous Found run 3083
2021-05-21T08:44:15-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3083 already downloaded to 2021/05/19/pr/UNK/f6ece8f/github-Benchmarks-3083-success; skipping
2021-05-21T08:44:15-0400 [INFO    ] tinuous Found run 3082
2021-05-21T08:44:15-0400 [INFO    ] tinuous Logs for benchmarks.yml (Benchmarks) #3082 already downloaded to 2021/05/19/pr/UNK/a377a29/github-Benchmarks-3082-success; skipping
2021-05-21T08:44:15-0400 [INFO    ] tinuous Found run 3081
Traceback (most recent call last):
  File "/home/datalad/miniconda3/envs/tinuous-dev/bin/tinuous", line 33, in <module>
    sys.exit(load_entry_point('tinuous', 'console_scripts', 'tinuous')())
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 989, in fetch
    for obj in ci.get_assets(cfg.types, artifacts=get_artifacts):
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 219, in get_assets
    event_id = self.get_event_id(run, run_event)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 252, in get_event_id
    self.client.search_issues(
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 39889.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

```
</details>

**Comment by jwodder** [comment]
@yarikoptic Two things:
* It appears that GitHub API rate limits reset on the hour, so waiting for the limit to reset could take quite a while.
* Using your new token, what does `curl -fsSL -H "Authorization: token $TOKEN" https://api.github.com/rate_limit` report?

**Comment by yarikoptic** [comment]
<details>
<summary>protocol</summary>

```shell
(tinuous-dev) datalad@smaug:/mnt/datasets/datalad/ci/logs$ ( source $PWD.secrets && curl -fsSL -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit && tinuous fetch && curl -fsSL -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit )
{
  "resources": {
    "core": {
      "limit": 5000,
      "used": 15,
      "remaining": 4985,
      "reset": 1621616402
    },
    "search": {
      "limit": 30,
      "used": 0,
      "remaining": 30,
      "reset": 1621613158
    },
    "graphql": {
      "limit": 5000,
      "used": 1,
      "remaining": 4999,
      "reset": 1621616571
    },
    "integration_manifest": {
      "limit": 5000,
      "used": 0,
      "remaining": 5000,
      "reset": 1621616698
    },
    "source_import": {
      "limit": 100,
      "used": 0,
      "remaining": 100,
      "reset": 1621613158
    },
    "code_scanning_upload": {
      "limit": 500,
      "used": 0,
      "remaining": 500,
      "reset": 1621616698
    }
  },
  "rate": {
    "limit": 5000,
    "used": 15,
    "remaining": 4985,
    "reset": 1621616402
  }
}
```

.... fetched some and then crashed. I reran and got 

```
(tinuous-dev) datalad@smaug:/mnt/datasets/datalad/ci/logs$ ( source $PWD.secrets && curl -fsSL -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit )
{
  "resources": {
    "core": {
      "limit": 5000,
      "used": 29,
      "remaining": 4971,
      "reset": 1621616402
    },
    "search": {
      "limit": 30,
      "used": 30,
      "remaining": 0,
      "reset": 1621613162
    },
    "graphql": {
      "limit": 5000,
      "used": 1,
      "remaining": 4999,
      "reset": 1621616571
    },
    "integration_manifest": {
      "limit": 5000,
      "used": 0,
      "remaining": 5000,
      "reset": 1621616724
    },
    "source_import": {
      "limit": 100,
      "used": 0,
      "remaining": 100,
      "reset": 1621613184
    },
    "code_scanning_upload": {
      "limit": 500,
      "used": 0,
      "remaining": 500,
      "reset": 1621616724
    }
  },
  "rate": {
    "limit": 5000,
    "used": 29,
    "remaining": 4971,
    "reset": 1621616402
  }
}

```

</details>

so it is the search-specific one which has too low of a limit to be used pragmatically :-/

**Comment by jwodder** [comment]
@yarikoptic I've created #52 in order to cache PR numbers for commit hashes, which should cut down on the number of searches made.

**Comment by yarikoptic** [comment]
unfortunately #52 did not help much.  I guess we might be doomed to abandon `search` approach.
FWIW here is the `config.yml` I am using
```
repo: datalad/datalad
vars:
  path_prefix: '{year}//{month}//{day}/{type}/{type_id}/{abbrev_commit}/{ci}-'
ci:
  github:
    path: '{path_prefix}{wf_name}-{number}-{common_status}/'
  travis:
    path: '{path_prefix}{number}-{common_status}/{job}.txt'
  appveyor:
    path: '{path_prefix}{number}-{common_status}/{job}.txt'
    accountName: mih
    projectSlug: datalad
since: 2021-05-19T00:00:00Z
types: [cron, pr, push]
#secrets:
  #github: '\b(v1\.)?[a-f0-9]{40}\b'
  #docker-hub: '\b[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}\b'
  #appveyor: '\b(v2\.)?[a-z0-9]{20}\b'
  #travis: '\b[a-zA-Z0-9]{22}\b'
  #aws: '\b[a-zA-Z0-9+/]{40}\b'
datalad:
  enabled: true
```

**Comment by jwodder** [comment]
@yarikoptic The next best approach to using a search is the ["List pull requests associated with a commit"](https://docs.github.com/en/rest/reference/repos#list-pull-requests-associated-with-a-commit) preview endpoint, which appears to ignore PRs not made to the default branch, so in datalad's case, commits to PRs to `maint` would be missing their PR numbers.

**Comment by yarikoptic** [comment]
Yikes, worth filling an issue with GitHub since then it should've been "List pull requests against default branch associated with a commit"

**Comment by jwodder** [comment]
@yarikoptic I did file an issue, but I wouldn't hold my breath waiting for a resolution.  Should I use the endpoint anyway?

**Comment by yarikoptic** [comment]
eh... I guess it shouldn't hurt as the first step before resorting to `search` as an ultimate workaround.

Also, could you remind me -- all that is just to figure out which PR a given commit is associated with whenever the PR already "moved" on to a newer state, i.e. if PR is "fresh" none of this should be needed.  And I just should setup more frequent cron jobs to always stay on "fresh" state to avoid hitting this use case.  Or it would always be needed, even for fresh PRs?

**Comment by jwodder** [comment]
@yarikoptic This lookup is needed whenever the PR information isn't present in the workflow run object.  I believe that the PR info is omitted if the PR is closed, and I seem to recall seeing it omitted a few other times when the PR was still open.  Ideally, the PR information should always be included in the workflow run for PR activity, and I opened a support ticket to that effect a few months ago, but the API continues to not always report this information.

**Comment by jwodder** [comment]
@yarikoptic FYI, GitHub got back to me about "List pull requests associated with a commit" not returning PRs to the non-default branch.  It turns out that what's actually happening is that the endpoint doesn't return PRs made from forks, and this is intended.  In order to get the PR number, you apparently have to make the request on the fork, but knowing what the fork is requires knowing the PR in the first place.

**Comment by yarikoptic** [comment]
I could be wrong, but I think we are already waiting/retrying later.  Please reopen if I am wrong
