### ISSUE TITLE
skip upon 410 (Gone)

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#85]
logs could be gone from CI. I don't think we can do anything about those.  The only thing I wonder if we should place some placeholder to mark (so to not re-try)

```
2021-06-09T14:03:16-0400 [INFO    ] tinuous Downloading logs for build-macos.yaml (Build git-annex on macOS) #196 to builds/2021/03/cron-20210311/build-macos.yaml-196-3c9e16a9-success
Traceback (most recent call last):
  File "/home/datalad/miniconda3/envs/tinuous-dev/bin/tinuous", line 33, in <module>
    sys.exit(load_entry_point('tinuous', 'console_scripts', 'tinuous')())
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 126, in fetch
    paths = obj.download(Path(path))
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/github.py", line 262, in download
    r = self.client.get(self.logs_url)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/base.py", line 78, in get
    r.raise_for_status()
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.github.com/repos/datalad/git-annex/actions/runs/641344063/logs
```

**Comment by jwodder** [comment]
@yarikoptic 

> may be if tinuous updated a timestamp in .dlstate.json as soon as it progressed forward for a CI, then we would not even retry too many if we need to restart without prior clean finish.

That wouldn't work, as all the CI APIs return builds in reverse chronological order.  No, there's no option to reverse the order.

**Comment by yarikoptic** [comment]
then we could have kept a list of known to be missing builds with their dates and filter them away upon progressing timestamp.  Well, let's proceed without that and if real needs comes, I will file a dedicated issue.
